library(S4Vectors)
library(limma)
library(edgeR)
coolcat_no_filter <-function (fmt, vals = character(), exdent = 2, ...)
{
    lbls <- paste(S4Vectors:::selectSome(vals), collapse = " ")
    txt <- sprintf(fmt, length(vals), lbls)
    cat(strwrap(txt, exdent = exdent, ...), sep = "\n")
}

setMethod(show, "EList", function (object) {
    cat("class:", class(object), "\n")
    cat("dim:", dim(object), "\n")
    rownames <- rownames(object)
    if (!is.null(rownames))
        coolcat("rownames (%d): %s\n", rownames)
    else cat("rownames: NULL\n")
    coolcat("genes table names (%d): %s\n", names(object$genes))
    colnames <- colnames(object)
    if (!is.null(colnames))
        coolcat("colnames(%d): %s\n", colnames)
    else cat("colnames: NULL\n")
    coolcat("targets table names (%d): %s\n", names(object$targets))
    coolcat_no_filter("E (%d): %s\n", as.vector(object$E))
    if (!is.null(object$weights))
        coolcat_no_filter("weights (%d): %s\n", as.vector(object$weights))
    other_names <- setdiff(names(object), c("E", "weights", "targets", "genes"))
    if (length(other_names) > 0)
        coolcat("Other elements (%d): %s\n", other_names)
    other_slot_names <- setdiff(slotNames(object), ".Data")
    if (length(other_slot_names) > 0)
        coolcat("Other slots (%d):  %s\n", other_slot_names)
})

setMethod(show, "DGEList", function (object) {
    cat("class:", class(object), "\n")
    cat("dim:", dim(object), "\n")
    rownames <- rownames(object)
    if (!is.null(rownames))
        coolcat("rownames (%d): %s\n", rownames)
    else cat("rownames: NULL\n")
    if (!is.null(object$genes))
        coolcat("genes table names (%d): %s\n", names(object$genes))
    colnames <- colnames(object)
    if (!is.null(colnames))
        coolcat("colnames(%d): %s\n", colnames)
    else cat("colnames: NULL\n")
    coolcat("samples table names (%d): %s\n", names(object$samples))
    coolcat_no_filter("counts (%d): %s\n", as.vector(object$counts))
    if (!is.null(object$weights))
        coolcat_no_filter("weights (%d): %s\n", as.vector(object$weights))
    other_names <- setdiff(names(object), c("counts", "weights", "samples", "genes"))
    if (length(other_names) > 0)
        coolcat("Other elements (%d): %s\n", other_names)
    other_slot_names <- setdiff(slotNames(object), ".Data")
    if (length(other_slot_names) > 0)
        coolcat("Other slots (%d):  %s\n", other_slot_names)
})

setMethod(show, "MArrayLM", function(object) {
    cat("class:", class(object), "\n")
    cat("dim:", dim(object), "\n")
    rownames <- rownames(object)
    if (!is.null(rownames))
        coolcat("rownames (%d): %s\n", rownames)
    else cat("rownames: NULL\n")
    if (!is.null(object$genes))
        coolcat("genes table names (%d): %s\n", names(object$genes))
    ## Add backticks when needed for disambiguation
    colnames <- sapply(colnames(object), function(x) deparse1(sym(x), backtick = TRUE))
    if (!is.null(colnames))
        coolcat("coef names (%d): %s\n", colnames)
    else cat("coef names: NULL\n")
    other_names <- setdiff(names(object), c("genes"))
    if (length(other_names) > 0)
        coolcat("Other elements (%d): %s\n", other_names)
    other_slot_names <- setdiff(slotNames(object), ".Data")
    if (length(other_slot_names) > 0)
        coolcat("Other slots (%d):  %s\n", other_slot_names)
})
